"""Built-in recipes shown on the home page and indexed into the RAG system."""

BUILT_IN_RECIPES = [
    {
        "title": "Classic Margherita Pizza",
        "category": "Italian",
        "cuisine": "Italian",
        "dietary": ["Vegetarian"],
        "time": "30 min",
        "prep_time": "10 min",
        "cook_time": "15 min",
        "servings": "4 servings",
        "img": "pictures/Margherita-Pizza.webp",
        "description": "A simple yet delicious pizza with fresh mozzarella, tomatoes, and basil. This authentic Italian recipe brings the taste of Naples to your kitchen.",
        "ingredients": [
            "1 pizza dough ball",
            "1 cup tomato sauce",
            "8 oz fresh mozzarella",
            "Fresh basil leaves",
            "2 tbsp olive oil",
            "Salt and pepper to taste",
            "1 clove garlic, minced",
        ],
        "instructions": [
            "Preheat your oven to 475°F (245°C) with a pizza stone inside.",
            "Roll out the pizza dough on a floured surface to about 12 inches in diameter.",
            "Spread the tomato sauce evenly over the dough, leaving a 1-inch border.",
            "Tear the mozzarella into pieces and distribute over the sauce.",
            "Drizzle with olive oil and add minced garlic.",
            "Bake for 12-15 minutes until the crust is golden and cheese is bubbly.",
            "Remove from oven and top with fresh basil leaves. Season with salt and pepper.",
        ],
    },
    {
        "title": "Creamy Chicken Alfredo Pasta",
        "category": "Pasta",
        "cuisine": "Italian",
        "dietary": ["None"],
        "time": "25 min",
        "prep_time": "5 min",
        "cook_time": "20 min",
        "servings": "4 servings",
        "img": "pictures/homemade-chicken-alfredo-1-9.jpg",
        "description": "Rich and creamy fettuccine alfredo with tender chicken, parmesan, and a velvety sauce.",
        "ingredients": [
            "12 oz fettuccine pasta",
            "2 chicken breasts, sliced",
            "1 cup heavy cream",
            "1 cup grated parmesan cheese",
            "3 cloves garlic, minced",
            "3 tbsp butter",
            "Salt and pepper to taste",
            "Fresh parsley, chopped",
        ],
        "instructions": [
            "Cook fettuccine according to package directions; reserve 1/2 cup pasta water.",
            "Season chicken with salt and pepper, sauté in butter until golden, about 6-7 minutes.",
            "Add garlic and cook for 30 seconds until fragrant.",
            "Pour in heavy cream and bring to a gentle simmer.",
            "Stir in parmesan cheese until melted and sauce thickens.",
            "Toss cooked pasta in the sauce; add pasta water to loosen if needed.",
            "Garnish with parsley and extra parmesan, then serve immediately.",
        ],
    },
    {
        "title": "Fresh Garden Salad Bowl",
        "category": "Salad",
        "cuisine": "Mediterranean",
        "dietary": ["Vegetarian", "Vegan", "Gluten-free"],
        "time": "15 min",
        "prep_time": "15 min",
        "cook_time": "0 min",
        "servings": "2 servings",
        "img": "pictures/fresh-garden-salad.jpg",
        "description": "A vibrant bowl of fresh greens, crunchy vegetables, and a zesty vinaigrette.",
        "ingredients": [
            "4 cups mixed greens",
            "1 cup cherry tomatoes, halved",
            "1 cucumber, sliced",
            "1/2 red onion, thinly sliced",
            "1 avocado, diced",
            "1/4 cup olive oil",
            "2 tbsp lemon juice",
            "Salt and pepper to taste",
        ],
        "instructions": [
            "Wash and dry all greens and vegetables thoroughly.",
            "Combine mixed greens, tomatoes, cucumber, and red onion in a large bowl.",
            "Whisk olive oil, lemon juice, salt, and pepper to make the dressing.",
            "Drizzle dressing over the salad and toss gently.",
            "Top with diced avocado just before serving.",
            "Serve immediately for the best freshness and crunch.",
        ],
    },
    {
        "title": "Chocolate Lava Cake",
        "category": "Dessert",
        "cuisine": "French",
        "dietary": ["Vegetarian"],
        "time": "20 min",
        "prep_time": "10 min",
        "cook_time": "10 min",
        "servings": "2 servings",
        "img": "pictures/lava-cake-.jpg",
        "description": "Decadent individual chocolate cakes with a molten center, perfect for date night.",
        "ingredients": [
            "4 oz bittersweet chocolate, chopped",
            "1/2 cup unsalted butter",
            "2 large eggs",
            "2 large egg yolks",
            "1/4 cup granulated sugar",
            "2 tbsp all-purpose flour",
            "Pinch of salt",
            "Powdered sugar for dusting",
        ],
        "instructions": [
            "Preheat oven to 425°F (220°C) and butter two ramekins.",
            "Melt chocolate and butter together until smooth.",
            "Whisk eggs, yolks, and sugar until pale and thick.",
            "Fold in melted chocolate, then flour and salt.",
            "Divide batter between ramekins and bake for 10-12 minutes.",
            "Edges should be set but the center still soft.",
            "Invert onto plates, dust with powdered sugar, and serve warm.",
        ],
    },
    {
        "title": "Grilled Salmon with Lemon",
        "category": "Seafood",
        "cuisine": "Mediterranean",
        "dietary": ["Gluten-free", "Dairy-free"],
        "time": "20 min",
        "prep_time": "5 min",
        "cook_time": "15 min",
        "servings": "4 servings",
        "img": "pictures/Salmon-With-Lemon-Herb.jpg",
        "description": "Flaky grilled salmon brushed with lemon, garlic, and herbs — light and healthy.",
        "ingredients": [
            "4 salmon fillets (6 oz each)",
            "2 tbsp olive oil",
            "2 lemons (juice + zest)",
            "3 cloves garlic, minced",
            "1 tbsp fresh dill, chopped",
            "Salt and pepper to taste",
            "Lemon wedges for serving",
        ],
        "instructions": [
            "Preheat grill to medium-high heat.",
            "Mix olive oil, lemon juice, zest, garlic, and dill in a bowl.",
            "Brush salmon with the marinade and season with salt and pepper.",
            "Place salmon skin-side down on the grill.",
            "Grill for 4-5 minutes per side until flaky and opaque.",
            "Serve with lemon wedges and extra dill.",
        ],
    },
    {
        "title": "Vegetarian Tacos",
        "category": "Mexican",
        "cuisine": "Mexican",
        "dietary": ["Vegetarian"],
        "time": "30 min",
        "prep_time": "10 min",
        "cook_time": "20 min",
        "servings": "4 servings",
        "img": "pictures/cuban-vegetarian-.jpg",
        "description": "Hearty vegetarian tacos packed with seasoned black beans, corn, and fresh toppings.",
        "ingredients": [
            "8 corn tortillas",
            "1 can black beans, drained",
            "1 cup corn kernels",
            "1 bell pepper, diced",
            "1 small onion, diced",
            "1 tsp cumin",
            "1 tsp chili powder",
            "1 avocado, sliced",
            "Fresh cilantro and lime wedges",
        ],
        "instructions": [
            "Heat oil in a skillet over medium heat.",
            "Sauté onion and bell pepper until soft, about 5 minutes.",
            "Add black beans, corn, cumin, and chili powder. Cook 5 more minutes.",
            "Warm tortillas in a dry pan or directly over a flame.",
            "Fill tortillas with the bean mixture.",
            "Top with avocado, cilantro, and a squeeze of lime.",
        ],
    },
]
